In [26]:
from FFNN import FFNN
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
import random
import numpy as np
iris = datasets.load_iris()
x = iris.data.tolist()  # we only take the first two features.

y = iris.target

target = []
for i in range(len(y)):
    if (y[i] == 0):
        target.append([1,0,0])
    elif(y[i] == 1):
        target.append([0,1,0])
    else:
        target.append([0,0,1])


data = []
for i in range(len(x)):
    data.append((x[i],target[i]))

trainingLen = (len(data) * 9) // 10
testLen = len(data) - trainingLen

random.seed(0)
random.shuffle(data)
x = []
target = []
x_test = []
target_test = []
for d in range (len(data)):
    if (d < trainingLen):
        x.append(data[d][0])
        target.append(data[d][1])
    else:
        x_test.append(data[d][0])
        target_test.append(data[d][1])

In [27]:
ffnn = FFNN("IrisModel4.txt")
ffnn.printModel()
ffnn.setBackwardParameter(target, 0.1)
ffnn.backward(1, 0.1, 1000, x)

Layer 1:
Fungsi Aktivasi:  linear
Neuron 1: [0.1, 0.1, 0.1, 0.1, 0.1]
Neuron 2: [0.1, 0.1, 0.1, 0.1, 0.1]
Layer 2:
Fungsi Aktivasi:  linear
Neuron 1: [1.0, 1.0, 1.0]
Neuron 2: [1.0, 1.0, 1.0]
Neuron 3: [1.0, 1.0, 1.0]
Layer 3:
Fungsi Aktivasi:  softmax
Neuron 1: [1.0, 1.0, 1.0, 0.5]
Neuron 2: [1.0, 0.5, 0.5, 0.5]
Neuron 3: [1.0, 0.5, 0.5, 1.0]
Layer 1:
Fungsi Aktivasi:  linear
Neuron 1: [0.5257120832629552, 1.2361772108341045, 0.9625620025604665, -0.9472367533864436, -1.209726023999975]
Neuron 2: [0.46970020941141294, 0.8718934638075373, 0.768886726775412, -1.0316665816713222, -1.1917885167181452]
Layer 2:
Fungsi Aktivasi:  linear
Neuron 1: [2.4616323804598075, 1.6777922036609725, 0.6176249145472962]
Neuron 2: [1.212881510915601, 2.1895384380213705, -0.19079671608845014]
Neuron 3: [-1.0706638945059965, -3.091381285263246, 1.5639771660118813]
Layer 3:
Fungsi Aktivasi:  softmax
Neuron 1: [-13.947642028865502, 20.10555550068345, 15.108782873057232, 29.86983792688108]
Neuron 2: [15.5093393

In [28]:
#Set classifier
clf = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(5, ), random_state=1, max_iter=10000, batch_size= 1, learning_rate_init=0.03)
#Keterangan Parameter :
# solver "adam" untuk gradient descent
# hidden layer sizes sebesar 5
# max_iter, iterasi maksimum 1000
# batch_size, besar batch 10
# learning_rate_init, learning rate 

# clf.fit(X, y)
clf.fit(x,target)

# clf.predict([[5.4, 3.9, 1.7, 0.4],[6.5, 3. , 5.2, 2. ]])
clfResult = clf.predict(x_test)
# print(x)
# print(target)
print(clfResult)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]]


In [29]:
ffnn.printModel()
count = 0
for i in range(len(x_test)):
    pred = np.round(np.array(ffnn.predict(x_test[i]))).tolist()
    print("IrisModel: ", pred, "target: ", target_test[i])
    if (pred == target_test[i]):
        count+=1
print(f"IrisModel Correct count: {count}/{len(x_test)}")

Layer 1:
Fungsi Aktivasi:  linear
Neuron 1: [0.5257120832629552, 1.2361772108341045, 0.9625620025604665, -0.9472367533864436, -1.209726023999975]
Neuron 2: [0.46970020941141294, 0.8718934638075373, 0.768886726775412, -1.0316665816713222, -1.1917885167181452]
Layer 2:
Fungsi Aktivasi:  linear
Neuron 1: [2.4616323804598075, 1.6777922036609725, 0.6176249145472962]
Neuron 2: [1.212881510915601, 2.1895384380213705, -0.19079671608845014]
Neuron 3: [-1.0706638945059965, -3.091381285263246, 1.5639771660118813]
Layer 3:
Fungsi Aktivasi:  softmax
Neuron 1: [-13.947642028865502, 20.10555550068345, 15.108782873057232, 29.86983792688108]
Neuron 2: [15.509339313215024, 10.061765266851907, -5.612720718689057, 3.114035278567247]
Neuron 3: [1.4383027156518478, -28.167320767534093, -7.496062154367859, -30.983873205449544]
IrisModel:  [0.0, 0.0, 1.0] target:  [0, 0, 1]
IrisModel:  [0.0, 0.0, 1.0] target:  [0, 1, 0]
IrisModel:  [1.0, 0.0, 0.0] target:  [1, 0, 0]
IrisModel:  [0.0, 0.0, 1.0] target:  [0, 0,

In [30]:
#Ubah jadi target 0,1,2
def convertEncoding(array_input):
    array_output = []
    for input in array_input:
        array_output.append(input.index(max(input)))
    return array_output

hasil_predict_unprocessed = ffnn.predictBatch(x_test)
hasil_predict = convertEncoding(hasil_predict_unprocessed)
target_predict = convertEncoding(target_test)
clf_result = convertEncoding(clfResult.tolist())
print("Hasil predict iris model: ",hasil_predict)
print("Hasil predict sklearn: ",clf_result)
print("Target: ",target_predict)

Hasil predict iris model:  [2, 2, 0, 2, 1, 1, 2, 1, 2, 2, 2, 1, 0, 2, 1]
Hasil predict sklearn:  [2, 1, 0, 1, 1, 1, 2, 1, 2, 2, 2, 1, 0, 2, 1]
Target:  [2, 1, 0, 2, 1, 1, 2, 1, 2, 2, 2, 1, 0, 2, 1]


In [31]:
#SKLearn model example
from sklearn.metrics import confusion_matrix
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]
confusion_matrix(y_true, y_pred)

array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]], dtype=int64)

In [35]:
print("Hasil confusion matrix library sklearn")
print("Hasil predict iris model: \n",confusion_matrix(target_predict,hasil_predict))
print("Hasil predict sklearn: \n",confusion_matrix(target_predict,clf_result))

Hasil confusion library sklearn
Hasil predict iris model: 
 [[2 0 0]
 [0 5 1]
 [0 0 7]]
Hasil predict sklearn: 
 [[2 0 0]
 [0 6 0]
 [0 1 6]]


In [40]:
#Confusion matrix
#True positive, false positive, true negative, false negative
#Accuracy,precision,recall,F1
#Catatan: baris true, column pred (ngikutin sklearn)
def getConfusionMatrix(target,prediction):
    n = len(set(target))
    confusion_matrix = [[0 for i in range(n)] for j in range(n)]
    for i in range(len(target)):
        true = int(target[i])
        pred = int(prediction[i])
        confusion_matrix[true][pred] += 1
    return confusion_matrix

print("Hasil confusion matrix implementasi")
print("Hasil predict iris model: \n",getConfusionMatrix(target_predict,hasil_predict))
print("Hasil predict sklearn: \n",getConfusionMatrix(target_predict,clf_result))

Hasil confusion matrix implementasi
Hasil predict iris model: 
 [[2, 0, 0], [0, 5, 1], [0, 0, 7]]
Hasil predict sklearn: 
 [[2, 0, 0], [0, 6, 0], [0, 1, 6]]
