# FFNN sendiri
gak beres, pake yang sk learn aja

In [1]:
from FFNN import FFNN
from sklearn import datasets
import random
import numpy as np

# load dataset
iris = datasets.load_iris()
x = iris.data.tolist()  # we only take the first two features.

y = iris.target

target = []
for i in range(len(y)):
    if (y[i] == 0):
        target.append([1,0,0])
    elif(y[i] == 1):
        target.append([0,1,0])
    else:
        target.append([0,0,1])


data = []
for i in range(len(x)):
    data.append((x[i],target[i]))



In [2]:
# separate test and training data
trainingLen = (len(data) * 9) // 10
testLen = len(data) - trainingLen

random.seed(0)
random.shuffle(data)
x = []
target = []
x_test = []
target_test = []
for d in range (len(data)):
    if (d < trainingLen):
        x.append(data[d][0])
        target.append(data[d][1])
    else:
        x_test.append(data[d][0])
        target_test.append(data[d][1])

In [3]:
#  split training data to 10 part
def split(a, n):
    k, m = divmod(len(a), n)
    return [a[i*k+min(i, m):(i+1)*k+min(i+1, m)] for i in range(n)]
x_splitted = split(x, 10)
target_splitted = split(target, 10)

In [4]:
# create temp model and current model for iteration
model_temp = FFNN("IrisModel4.txt")
model_temp.printModel()
model_temp.setBackwardParameter(target, 0.1)

model_current = FFNN("IrisModel4.txt")
model_current.printModel()
model_current.setBackwardParameter(target, 0.1)


Layer 1:
Fungsi Aktivasi:  linear
Neuron 1: [0.1, 0.1, 0.1, 0.1, 0.1]
Neuron 2: [0.1, 0.1, 0.1, 0.1, 0.1]
Layer 2:
Fungsi Aktivasi:  linear
Neuron 1: [1.0, 1.0, 1.0]
Neuron 2: [1.0, 1.0, 1.0]
Neuron 3: [1.0, 1.0, 1.0]
Layer 3:
Fungsi Aktivasi:  softmax
Neuron 1: [1.0, 1.0, 1.0, 0.5]
Neuron 2: [1.0, 0.5, 0.5, 0.5]
Neuron 3: [1.0, 0.5, 0.5, 1.0]
Layer 1:
Fungsi Aktivasi:  linear
Neuron 1: [0.1, 0.1, 0.1, 0.1, 0.1]
Neuron 2: [0.1, 0.1, 0.1, 0.1, 0.1]
Layer 2:
Fungsi Aktivasi:  linear
Neuron 1: [1.0, 1.0, 1.0]
Neuron 2: [1.0, 1.0, 1.0]
Neuron 3: [1.0, 1.0, 1.0]
Layer 3:
Fungsi Aktivasi:  softmax
Neuron 1: [1.0, 1.0, 1.0, 0.5]
Neuron 2: [1.0, 0.5, 0.5, 0.5]
Neuron 3: [1.0, 0.5, 0.5, 1.0]


In [5]:
# fill and compare 10 model to find the best one
for i in range(10):
    model_temp.setBackwardParameter(target_splitted[i], 0.1)
    model_temp.backward(1, 0.1, 1000, x_splitted[i])
    if(model_temp.cumulative_error < model_current.cumulative_error):
        model_current = model_temp
        model_current.printModel()

Layer 1:
Fungsi Aktivasi:  linear
Neuron 1: [0.7528500196264457, 0.7799674429942154, 0.761643600026739, -1.6952185139024372, -1.609764771961396]
Neuron 2: [0.6831320600706465, 0.628481677404726, 0.6634641218392227, -1.718460644201833, -1.575987746407079]
Layer 2:
Fungsi Aktivasi:  linear
Neuron 1: [2.178134622848769, 1.3982838337192756, 0.992413813581655]
Neuron 2: [1.337955574515379, -0.9072081880384507, -0.5723609938159431]
Neuron 3: [2.0763527762335823, -0.5644073908338695, -0.17134524522877592]
Layer 3:
Fungsi Aktivasi:  softmax
Neuron 1: [-0.28676433687363, 5.327375168269749, 2.633886554956812, 0.9066672037486055]
Neuron 2: [7.133063534061586, 3.4020577471297275, 1.5471809349666783, 3.9399218685219677]
Neuron 3: [-3.8462991971879483, -6.729432915399462, -2.1810674899234974, -2.846589072270578]
iter:  241
error:  0.09804865675894549
Layer 1:
Fungsi Aktivasi:  linear
Neuron 1: [0.7528500196264457, 0.7799674429942154, 0.761643600026739, -1.6952185139024372, -1.609764771961396]
Neuron

In [6]:
# print model terbaik dan error
model_current.printModel()
print("Error: ",model_current.cumulative_error)

Layer 1:
Fungsi Aktivasi:  linear
Neuron 1: [0.7474744345411907, 0.6104520447399902, 0.649531040314035, -1.8606582085933447, -1.6983683269527843]
Neuron 2: [0.8066758842226788, 1.4873366999928934, 1.072158078703072, -1.042397604289936, -1.3536941297695362]
Layer 2:
Fungsi Aktivasi:  linear
Neuron 1: [2.0504547740444945, 1.4872628282844536, -2.2226134839383915]
Neuron 2: [1.0876072278720348, -1.4373171342918412, 1.0775485803840363]
Neuron 3: [1.1879541371167086, -0.40481471465539537, -2.6312374497538604]
Layer 3:
Fungsi Aktivasi:  softmax
Neuron 1: [0.2793244647178938, 4.753270758455161, -13.888511613696851, -18.540171703245093]
Neuron 2: [9.422272584757243, 5.782023795203743, 0.9510982497023931, -10.548248929206961]
Neuron 3: [-6.701597049475175, -8.535294553658904, 14.937413363994448, 31.088420632452042]
Error:  7.254197242903399e-13


In [7]:
#Predict best model
#Ubah jadi target 0,1,2
def convertEncoding(array_input):
    array_output = []
    for input in array_input:
        array_output.append(input.index(max(input)))
    return array_output

hasil_predict_unprocessed = model_current.predictBatch(x_test)
hasil_predict = convertEncoding(hasil_predict_unprocessed)
target_predict = convertEncoding(target_test)
print("Hasil predict iris model: ",hasil_predict)
print("Target: ",target_predict)

Hasil predict iris model:  [2, 1, 0, 1, 1, 1, 2, 1, 2, 2, 2, 1, 0, 2, 1]
Target:  [2, 1, 0, 2, 1, 1, 2, 1, 2, 2, 2, 1, 0, 2, 1]


In [8]:
#Confusion matrix
#True positive, false positive, true negative, false negative
#Catatan: baris true, column pred (ngikutin sklearn)
def getConfusionMatrix(target,prediction):
    n = len(set(target))
    confusion_matrix = [[0 for i in range(n)] for j in range(n)]
    for i in range(len(target)):
        true = int(target[i])
        pred = int(prediction[i])
        confusion_matrix[true][pred] += 1
    return np.array(confusion_matrix) 

print("Hasil confusion matrix implementasi")
print("Hasil predict iris model: \n",getConfusionMatrix(target_predict,hasil_predict))

Hasil confusion matrix implementasi
Hasil predict iris model: 
 [[2 0 0]
 [0 6 0]
 [0 1 6]]


# pake sklearn

In [27]:

# evaluate a logistic regression model using k-fold cross-validation
from sklearn import datasets
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import KFold, train_test_split
from sklearn.neural_network import MLPClassifier
# create dataset
iris = datasets.load_iris()
X = iris.data  # we only take the first two features.
y = iris.target
X_train, X_test_final, y_train, y_test_final = train_test_split(X, y, test_size=0.33, random_state=1)

# prepare the cross-validation procedure
cv = KFold(n_splits=10, shuffle=False)

# create model/classifier
model = MLPClassifier(solver='adam', alpha=1e-5,hidden_layer_sizes=(15, ), random_state=1, max_iter=10000, batch_size= 1, learning_rate_init=0.03)

# cross validate
acc_score = []
best_acc_score = 0
best_data = [[], []]
for train_index , test_index in cv.split(X):
    X_train , X_test = X[train_index,:],X[test_index,:]
    y_train , y_test = y[train_index] , y[test_index]
     
    model.fit(X_train,y_train)
    pred_values = model.predict(X_test)
    
    acc = accuracy_score(pred_values , y_test)
    acc_score.append(acc)
    if(acc > best_acc_score):
        best_data[0] = X_train
        best_data[1] = y_train
     
avg_acc_score = sum(acc_score)/10
model.fit(best_data[0], best_data[1])
# report performance
print('accuracy of each fold - {}'.format(acc_score))
print('Avg accuracy : {}'.format(avg_acc_score))


accuracy of each fold - [1.0, 1.0, 1.0, 1.0, 0.8, 0.8666666666666667, 1.0, 1.0, 1.0, 1.0]
Avg accuracy : 0.9666666666666666


In [28]:
train_result = model.predict(X_test_final)
print("y_true:", y_test_final)
print("y_pred:", train_result)
print("confusion matriks:")
print(confusion_matrix(y_test_final, train_result))

y_true: [0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 2 2 1 2 0 0 0 1]
y_pred: [0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 2 2 1 2 0 0 0 1]
confusion matriks:
[[17  0  0]
 [ 0 18  1]
 [ 0  0 14]]
